class Property {
  final String id;
  final String title;
  final String location;
  final String imageUrl;
  final List<String> galleryImages;
  final double price;
  final double rating;
  final int reviews;
  final String category;
  final List<String> amenities;
  final String description;
  final String hostName;
  final String hostImageUrl;
  final int guests;
  final int bedrooms;
  final int beds;
  final int bathrooms;
  final String area;
  final String type; // 'Sale' or 'Rent'
  final String agentPhone;
  final String agentWhatsapp;
  final double latitude;
  final double longitude;
  final String status; // 'pending', 'published', 'rejected'
  final String? hostId;

  final int hostReviews;
  final double hostRating;
  final int hostExperienceYears;
  final String hostBio;
  final int hostJoinedYear;
  final String? hostEducation;
  final String? hostExtraInfo;

  final bool isGuestFavorite;

  // Step 7: House Rules & Settings
  final bool noSmoking;
  final bool noParties;
  final bool petsAllowed;
  final String checkInTime;
  final String checkOutTime;
  final String cancellationPolicy;
  final List<String> quickRules;

  // Step 2: Address Details
  final String addressHouse;
  final String addressStreet;
  final String addressBlock;
  final String addressArea;
  final String addressLandmark;

  // Pricing & Discounts Details
  final double cleaningFee;
  final int weeklyDiscount;
  final int monthlyDiscount;

  Property({
    required this.id,
    required this.title,
    required this.location,
    required this.imageUrl,
    this.galleryImages = const [],
    required this.price,
    required this.rating,
    required this.reviews,
    required this.category,
    required this.description,
    required this.hostName,
    required this.hostImageUrl,
    this.hostId,
    this.amenities = const [],
    this.guests = 2,
    this.bedrooms = 1,
    this.beds = 1,
    this.bathrooms = 1,
    this.area = '10 Marla',
    this.type = 'Rent',
    this.agentPhone = '+923000000000',
    this.agentWhatsapp = '923000000000',
    this.latitude = 33.6844,
    this.longitude = 73.0479,
    this.hostReviews = 0,
    this.hostRating = 0.0,
    this.hostExperienceYears = 0,
    this.hostBio = '',
    this.hostJoinedYear = 2020,
    this.hostEducation,
    this.hostExtraInfo,
    this.isGuestFavorite = false,
    this.status = 'published',
    this.noSmoking = true,
    this.noParties = true,
    this.petsAllowed = false,
    this.checkInTime = '14:00',
    this.checkOutTime = '12:00',
    this.cancellationPolicy = 'Moderate - Full refund 5 days before',
    this.quickRules = const [],
    this.addressHouse = '',
    this.addressStreet = '',
    this.addressBlock = '',
    this.addressArea = '',
    this.addressLandmark = '',
    this.cleaningFee = 0.0,
    this.weeklyDiscount = 0,
    this.monthlyDiscount = 0,
  });

  Property copyWith({
    String? id,
    String? title,
    String? location,
    String? imageUrl,
    List<String>? galleryImages,
    double? price,
    double? rating,
    int? reviews,
    String? category,
    String? description,
    String? hostName,
    String? hostImageUrl,
    String? hostId,
    List<String>? amenities,
    int? guests,
    int? bedrooms,
    int? beds,
    int? bathrooms,
    String? area,
    String? type,
    String? agentPhone,
    String? agentWhatsapp,
    double? latitude,
    double? longitude,
    int? hostReviews,
    double? hostRating,
    int? hostExperienceYears,
    String? hostBio,
    int? hostJoinedYear,
    String? hostEducation,
    String? hostExtraInfo,
    bool? isGuestFavorite,
    String? status,
    bool? noSmoking,
    bool? noParties,
    bool? petsAllowed,
    String? checkInTime,
    String? checkOutTime,
    String? cancellationPolicy,
    List<String>? quickRules,
    String? addressHouse,
    String? addressStreet,
    String? addressBlock,
    String? addressArea,
    String? addressLandmark,
    double? cleaningFee,
    int? weeklyDiscount,
    int? monthlyDiscount,
  }) {
    return Property(
      id: id ?? this.id,
      title: title ?? this.title,
      location: location ?? this.location,
      imageUrl: imageUrl ?? this.imageUrl,
      galleryImages: galleryImages ?? this.galleryImages,
      price: price ?? this.price,
      rating: rating ?? this.rating,
      reviews: reviews ?? this.reviews,
      category: category ?? this.category,
      description: description ?? this.description,
      hostName: hostName ?? this.hostName,
      hostImageUrl: hostImageUrl ?? this.hostImageUrl,
      hostId: hostId ?? this.hostId,
      amenities: amenities ?? this.amenities,
      guests: guests ?? this.guests,
      bedrooms: bedrooms ?? this.bedrooms,
      beds: beds ?? this.beds,
      bathrooms: bathrooms ?? this.bathrooms,
      area: area ?? this.area,
      type: type ?? this.type,
      agentPhone: agentPhone ?? this.agentPhone,
      agentWhatsapp: agentWhatsapp ?? this.agentWhatsapp,
      latitude: latitude ?? this.latitude,
      longitude: longitude ?? this.longitude,
      hostReviews: hostReviews ?? this.hostReviews,
      hostRating: hostRating ?? this.hostRating,
      hostExperienceYears: hostExperienceYears ?? this.hostExperienceYears,
      hostBio: hostBio ?? this.hostBio,
      hostJoinedYear: hostJoinedYear ?? this.hostJoinedYear,
      hostEducation: hostEducation ?? this.hostEducation,
      hostExtraInfo: hostExtraInfo ?? this.hostExtraInfo,
      isGuestFavorite: isGuestFavorite ?? this.isGuestFavorite,
      status: status ?? this.status,
      noSmoking: noSmoking ?? this.noSmoking,
      noParties: noParties ?? this.noParties,
      petsAllowed: petsAllowed ?? this.petsAllowed,
      checkInTime: checkInTime ?? this.checkInTime,
      checkOutTime: checkOutTime ?? this.checkOutTime,
      cancellationPolicy: cancellationPolicy ?? this.cancellationPolicy,
      quickRules: quickRules ?? this.quickRules,
      addressHouse: addressHouse ?? this.addressHouse,
      addressStreet: addressStreet ?? this.addressStreet,
      addressBlock: addressBlock ?? this.addressBlock,
      addressArea: addressArea ?? this.addressArea,
      addressLandmark: addressLandmark ?? this.addressLandmark,
      cleaningFee: cleaningFee ?? this.cleaningFee,
      weeklyDiscount: weeklyDiscount ?? this.weeklyDiscount,
      monthlyDiscount: monthlyDiscount ?? this.monthlyDiscount,
    );
  }

  factory Property.fromJson(Map<String, dynamic> json, String documentId) {
    return Property(
      id: documentId,
      title: json['title'] ?? '',
      location: json['location'] ?? '',
      imageUrl: json['imageUrl'] ?? '',
      galleryImages: List<String>.from(json['galleryImages'] ?? []),
      price: (json['price'] ?? 0.0).toDouble(),
      rating: (json['rating'] ?? 0.0).toDouble(),
      reviews: (json['reviews'] ?? 0).toInt(),
      category: json['category'] ?? '',
      description: json['description'] ?? '',
      hostName: json['hostName'] ?? '',
      hostImageUrl: json['hostImageUrl'] ?? '',
      hostId: json['hostId'],
      amenities: List<String>.from(json['amenities'] ?? []),
      guests: (json['guests'] ?? 2).toInt(),
      bedrooms: (json['bedrooms'] ?? 1).toInt(),
      beds: (json['beds'] ?? 1).toInt(),
      bathrooms: (json['bathrooms'] ?? 1).toInt(),
      area: json['area'] ?? '10 Marla',
      type: json['type'] ?? 'Rent',
      agentPhone: json['agentPhone'] ?? '+923000000000',
      agentWhatsapp: json['agentWhatsapp'] ?? '923000000000',
      latitude: (json['latitude'] ?? 33.6844).toDouble(),
      longitude: (json['longitude'] ?? 73.0479).toDouble(),
      hostReviews: (json['hostReviews'] ?? 0).toInt(),
      hostRating: (json['hostRating'] ?? 0.0).toDouble(),
      hostExperienceYears: (json['hostExperienceYears'] ?? 0).toInt(),
      hostBio: json['hostBio'] ?? '',
      hostJoinedYear: (json['hostJoinedYear'] ?? 2020).toInt(),
      hostEducation: json['hostEducation'],
      hostExtraInfo: json['hostExtraInfo'],
      isGuestFavorite: json['isGuestFavorite'] ?? false,
      status: json['status'] ?? 'published',
      noSmoking: json['noSmoking'] ?? true,
      noParties: json['noParties'] ?? true,
      petsAllowed: json['petsAllowed'] ?? false,
      checkInTime: json['checkInTime'] ?? '14:00',
      checkOutTime: json['checkOutTime'] ?? '12:00',
      cancellationPolicy: json['cancellationPolicy'] ?? 'Moderate - Full refund 5 days before',
      quickRules: List<String>.from(json['quickRules'] ?? []),
      addressHouse: json['addressHouse'] ?? '',
      addressStreet: json['addressStreet'] ?? '',
      addressBlock: json['addressBlock'] ?? '',
      addressArea: json['addressArea'] ?? '',
      addressLandmark: json['addressLandmark'] ?? '',
      cleaningFee: (json['cleaningFee'] ?? 0.0).toDouble(),
      weeklyDiscount: (json['weeklyDiscount'] ?? 0).toInt(),
      monthlyDiscount: (json['monthlyDiscount'] ?? 0).toInt(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'title': title,
      'location': location,
      'imageUrl': imageUrl,
      'galleryImages': galleryImages,
      'price': price,
      'rating': rating,
      'reviews': reviews,
      'category': category,
      'description': description,
      'hostName': hostName,
      'hostImageUrl': hostImageUrl,
      'hostId': hostId,
      'amenities': amenities,
      'guests': guests,
      'bedrooms': bedrooms,
      'beds': beds,
      'bathrooms': bathrooms,
      'area': area,
      'type': type,
      'agentPhone': agentPhone,
      'agentWhatsapp': agentWhatsapp,
      'latitude': latitude,
      'longitude': longitude,
      'hostReviews': hostReviews,
      'hostRating': hostRating,
      'hostExperienceYears': hostExperienceYears,
      'hostBio': hostBio,
      'hostJoinedYear': hostJoinedYear,
      'hostEducation': hostEducation,
      'hostExtraInfo': hostExtraInfo,
      'isGuestFavorite': isGuestFavorite,
      'status': status,
      'noSmoking': noSmoking,
      'noParties': noParties,
      'petsAllowed': petsAllowed,
      'checkInTime': checkInTime,
      'checkOutTime': checkOutTime,
      'cancellationPolicy': cancellationPolicy,
      'quickRules': quickRules,
      'addressHouse': addressHouse,
      'addressStreet': addressStreet,
      'addressBlock': addressBlock,
      'addressArea': addressArea,
      'addressLandmark': addressLandmark,
      'cleaningFee': cleaningFee,
      'weeklyDiscount': weeklyDiscount,
      'monthlyDiscount': monthlyDiscount,
    };
  }
}


final mockProperties = [
  Property(
    id: '1',
    hostId: 'host_1',
    title: 'Luxury Hillside Cottage',
    location: 'Murree, Pakistan',
    imageUrl: 'https://images.unsplash.com/photo-1571171637578-41bc2dd41cd2?q=80&w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1571171637578-41bc2dd41cd2?q=80&w=800',
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?q=80&w=800',
      'https://images.unsplash.com/photo-1449156001488-8742d13bb222?q=80&w=800',
    ],
    price: 15500,
    rating: 4.8,
    reviews: 128,
    category: 'Cottages',
    type: 'Rent',
    area: '1 Kanal',
    description: 'Experience pure luxury in the heart of Murree. This stunning hillside cottage offers breathtaking views of the pine forests and snow-capped peaks. Perfect for families looking for a peaceful getaway with modern amenities including a cozy fireplace, heated floors, and a private balcony.',
    hostName: 'Abdul Rehman',
    agentPhone: '+923124567890',
    agentWhatsapp: '923124567890',
    latitude: 33.9070,
    longitude: 73.3941,
    hostImageUrl: 'https://i.pravatar.cc/150?u=abdul',
    amenities: ['Wifi', 'Heater', 'Fireplace', 'Parking', 'Kitchen'],
    guests: 6,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    hostReviews: 2378,
    hostRating: 4.88,
    hostExperienceYears: 4,
    hostJoinedYear: 2020,
    hostBio: 'I am a local from Murree. I love meeting new people and sharing the beauty of my hometown. I am available for any help you need during your stay.',
    hostEducation: 'University of Peshawar',
    hostExtraInfo: 'Born in the 90s',
    isGuestFavorite: true,
  ),
  Property(
    id: '2',
    hostId: 'host_2',
    title: 'Mountain View Resort',
    location: 'Hunza Valley, Pakistan',
    imageUrl: 'https://images.unsplash.com/photo-1524443169398-9aa1ceab67d5?q=80&w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1524443169398-9aa1ceab67d5?q=80&w=800',
      'https://images.unsplash.com/photo-1614560193164-81c815250325?q=80&w=800',
      'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?q=80&w=800',
    ],
    price: 12000,
    rating: 4.9,
    reviews: 95,
    category: 'Resort',
    type: 'Rent',
    area: '15 Marla',
    description: 'Breathtaking views of Rakaposhi and Ultar Sar right from your window. Our resort in Hunza Valley provides the authentic northern hospitality with a touch of modern comfort. Enjoy organic traditional food and explore the ancient forts nearby.',
    hostName: 'Saeed Hunzai',
    agentPhone: '+923112223334',
    agentWhatsapp: '923112223334',
    latitude: 36.3167,
    longitude: 74.6500,
    hostImageUrl: 'https://i.pravatar.cc/150?u=saeed',
    amenities: ['Wifi', 'Breakfast', 'Tour Guide', 'Parking', 'Garden'],
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    hostReviews: 1240,
    hostRating: 4.95,
    hostExperienceYears: 6,
    hostJoinedYear: 2018,
    hostBio: 'Welcome to Hunza! I have been hosting travelers for over 6 years. I can help with local tours and traditional food experiences.',
    isGuestFavorite: true,
  ),
  Property(
    id: '3',
    hostId: 'host_3',
    title: 'Heritage Style Suite',
    location: 'Gulberg, Lahore',
    imageUrl: 'https://images.unsplash.com/photo-1622547748225-3fc4abd2cca0?q=80&w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1622547748225-3fc4abd2cca0?q=80&w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=800',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=800',
    ],
    price: 8500,
    rating: 4.7,
    reviews: 210,
    category: 'Suites',
    type: 'Rent',
    area: '5 Marla',
    description: 'A stylish and contemporary apartment located in the heart of Gulberg. Minutes away from M.M. Alam Road and Liberty Market. Features floor-to-ceiling windows with a city view, 24/7 security, gym access, and a fully equipped kitchen.',
    hostName: 'Mariam Khan',
    agentPhone: '+923111111111',
    agentWhatsapp: '923111111111',
    latitude: 31.5204,
    longitude: 74.3587,
    hostImageUrl: 'https://i.pravatar.cc/150?u=mariam',
    amenities: ['High-speed Wifi', 'Gym', 'Security', 'Elevator', 'Smart TV'],
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    hostReviews: 850,
    hostRating: 4.75,
    hostExperienceYears: 3,
    hostJoinedYear: 2021,
    hostBio: 'Lahore is my favorite city and I am so happy to share it with you! I am a foodie and can recommend the best spots to eat.',
  ),
  Property(
    id: '4',
    hostId: 'host_4',
    title: 'Modern Riverside Villa',
    location: 'Swat Valley, Pakistan',
    imageUrl: 'https://images.unsplash.com/photo-1598091383021-15ddea10925d?q=80&w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1598091383021-15ddea10925d?q=80&w=800',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=800',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=800',
    ],
    price: 6000,
    rating: 4.6,
    reviews: 64,
    category: 'Villas',
    type: 'Sale',
    area: '2 Kanal',
    description: 'Immerse yourself in the local Swati culture. Our guest house is built in traditional stone architecture and offers a serene garden by the river. We provide farm-to-table breakfast and guided treks into the nearby valley.',
    hostName: 'Yousaf Ali',
    agentPhone: '+923214445556',
    agentWhatsapp: '923214445556',
    latitude: 34.7717,
    longitude: 72.3600,
    hostImageUrl: 'https://i.pravatar.cc/150?u=yousaf',
    amenities: ['Garden', 'Traditional Food', 'River View', 'Parking', 'Pets allowed'],
    guests: 8,
    bedrooms: 4,
    beds: 6,
    bathrooms: 3,
    hostReviews: 420,
    hostRating: 4.65,
    hostExperienceYears: 5,
    hostJoinedYear: 2019,
    hostBio: 'Hospitality is in our blood. My family has lived here for generations. We look forward to hosting you!',
  ),
  Property(
    id: '5',
    hostId: 'host_5',
    title: 'Ocean View Penthouse',
    location: 'Clifton, Karachi',
    imageUrl: 'https://images.unsplash.com/photo-1588666309990-d68f08e3d4a6?q=80&w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1588666309990-d68f08e3d4a6?q=80&w=800',
      'https://images.unsplash.com/photo-1600607687940-c52af096999a?q=80&w=800',
      'https://images.unsplash.com/photo-1600566752253-15a0178385e0?q=80&w=800',
    ],
    price: 25000,
    rating: 4.5,
    reviews: 42,
    category: 'Villas',
    type: 'Sale',
    area: '10 Marla',
    description: 'Exclusive beach front villa in Clifton. Enjoy the sea breeze from your private rooftop terrace. This spacious 4-bedroom villa is perfect for large groups and events. Equipped with state-of-the-art entertainment systems and a private servant quarter.',
    hostName: 'Zubair Shah',
    agentPhone: '+923331234567',
    agentWhatsapp: '923331234567',
    latitude: 24.8138,
    longitude: 67.0300,
    hostImageUrl: 'https://i.pravatar.cc/150?u=zubair',
    amenities: ['Private Beach', 'Rooftop Terrace', 'AC', 'Parking', 'Event Friendly'],
    guests: 10,
    bedrooms: 5,
    beds: 8,
    bathrooms: 4,
    hostReviews: 215,
    hostRating: 4.60,
    hostExperienceYears: 2,
    hostJoinedYear: 2022,
    hostBio: 'Karachi is a city of life! I am happy to offer this luxury space for your stay or special event.',
  ),
  Property(
    id: '6',
    hostId: 'host_6',
    title: 'Margalla Hill View',
    location: 'F-7, Islamabad',
    imageUrl: 'https://images.unsplash.com/photo-1533158307587-828f0a76ef46?q=80&w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1533158307587-828f0a76ef46?q=80&w=800',
      'https://images.unsplash.com/photo-1585412727339-54e4bae3bbf9?q=80&w=800',
      'https://images.unsplash.com/photo-1574362848149-11496d93a7c7?q=80&w=800',
    ],
    price: 18000,
    rating: 4.9,
    reviews: 87,
    category: 'Suites',
    type: 'Rent',
    area: '1 Kanal',
    description: 'The ultimate urban retreat in Islamabads most prestigious sector. Our suite offers panoramic views of the Margalla Hills. Features designer furniture, a workspace for professionals, and proximity to all major diplomatic and commercial hubs.',
    hostName: 'Farah Ahmed',
    agentPhone: '+923459998887',
    agentWhatsapp: '923459998887',
    latitude: 33.7167,
    longitude: 73.0500,
    hostImageUrl: 'https://i.pravatar.cc/150?u=farah',
    amenities: ['Office Desk', 'Mountain View', 'Fast Wifi', 'Security', 'Netflix'],
    guests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    hostReviews: 530,
    hostRating: 4.92,
    hostExperienceYears: 4,
    hostJoinedYear: 2020,
    hostBio: 'I value comfort and efficiency. My suite is designed for modern travelers who need a high-quality place to stay while in Islamabad.',
  ),
];

